#cloud-config
local-hostname: ${hostname}
instance-id: ${hostname}
network:
  version: 2
  ethernets:
    ens192:
      dhcp4: false
      addresses:
        - ${ip_address}/24
      gateway4: 10.10.69.1
      nameservers:
        search: [home]
        addresses: [8.8.8.8]
    ens224:
      dhcp4: false
wait-on-network:
  ipv4: true
